<?php

declare(strict_types=1);

namespace PowerSweeper\WebApp;

/**
 * Emit a static HTML preview scaffold from web IR (heuristic, not a Power Fx runtime).
 */
final class WebAppHtmlPreview
{
    /** @param array<string, mixed> $ir */
    public function render(array $ir): string
    {
        $title = (string) (($ir['document']['name'] ?? null) ?: 'Power Sweeper Web Preview');
        $screens = is_array($ir['screens'] ?? null) ? $ir['screens'] : [];
        $nav = is_array($ir['navigation'] ?? null) ? $ir['navigation'] : [];

        $navJson = json_encode($nav, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?: '[]';
        $screensJson = json_encode($screens, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?: '[]';

        $screenLinks = '';
        foreach ($screens as $s) {
            if (!is_array($s)) {
                continue;
            }
            $name = htmlspecialchars((string) ($s['name'] ?? ''), ENT_QUOTES);
            if ($name === '') {
                continue;
            }
            $screenLinks .= '<button type="button" class="nav-btn" data-screen="' . $name . '">' . $name . '</button>';
        }

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{$title}</title>
  <style>
    :root { --bg:#0f1419; --panel:#1a222c; --text:#e7ecf1; --muted:#9aa7b5; --accent:#3b82f6; --line:#2a3542; }
    * { box-sizing: border-box; }
    body { margin:0; font-family: "Segoe UI", system-ui, sans-serif; background:var(--bg); color:var(--text); }
    header { padding:1rem 1.25rem; border-bottom:1px solid var(--line); display:flex; gap:1rem; align-items:center; flex-wrap:wrap; }
    header h1 { font-size:1rem; margin:0; font-weight:600; }
    header p { margin:0; color:var(--muted); font-size:.85rem; }
    .nav { display:flex; gap:.4rem; flex-wrap:wrap; padding:.75rem 1.25rem; border-bottom:1px solid var(--line); }
    .nav-btn { background:var(--panel); color:var(--text); border:1px solid var(--line); border-radius:6px; padding:.35rem .7rem; cursor:pointer; }
    .nav-btn.active { border-color:var(--accent); background:#1e2a3a; }
    main { padding:1.25rem; max-width:960px; }
    .screen { display:none; }
    .screen.active { display:block; }
    .card { background:var(--panel); border:1px solid var(--line); border-radius:10px; padding:1rem; margin-bottom:.75rem; }
    .card h2 { margin:0 0 .5rem; font-size:1.05rem; }
    .meta { color:var(--muted); font-size:.8rem; margin-bottom:.75rem; }
    .ctrl { padding:.35rem 0; border-top:1px dashed var(--line); font-size:.9rem; }
    .ctrl:first-child { border-top:0; }
    .role { color:var(--accent); font-size:.75rem; text-transform:uppercase; letter-spacing:.04em; }
    .label { font-weight:500; }
    .path { color:var(--muted); font-size:.75rem; }
    footer { padding:1rem 1.25rem; color:var(--muted); font-size:.75rem; border-top:1px solid var(--line); }
  </style>
</head>
<body>
  <header>
    <h1>{$title}</h1>
    <p>Structural preview from Power Sweeper IR — not a live Power Apps runtime.</p>
  </header>
  <nav class="nav" id="nav">{$screenLinks}</nav>
  <main id="main"></main>
  <footer>Generated by Power Sweeper export_web_ir. Edit IR JSON then run web_to_power to apply label/navigation/document heuristics.</footer>
  <script>
    const screens = {$screensJson};
    const navigation = {$navJson};
    const main = document.getElementById('main');
    const nav = document.getElementById('nav');

    function renderControl(c, depth) {
      const labels = c.labels || {};
      const text = labels.Text || labels.AccessibleLabel || labels.Tooltip || '';
      const kids = (c.children || []).map(ch => renderControl(ch, depth + 1)).join('');
      if (!text && !kids && c.role === 'container') {
        return kids;
      }
      return '<div class="ctrl" style="padding-left:' + (depth * 12) + 'px">' +
        '<div><span class="role">' + (c.role || 'control') + '</span> ' +
        '<span class="label">' + escapeHtml(text || c.name) + '</span></div>' +
        '<div class="path">' + escapeHtml(c.name + ' · ' + (c.type || '')) + '</div>' +
        kids + '</div>';
    }

    function escapeHtml(s) {
      return String(s).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
    }

    function show(name) {
      [...nav.querySelectorAll('.nav-btn')].forEach(b => b.classList.toggle('active', b.dataset.screen === name));
      const s = screens.find(x => x.name === name) || screens[0];
      if (!s) { main.innerHTML = '<p class="meta">No screens in IR.</p>'; return; }
      const fromHere = navigation.filter(e => e.from === s.name);
      const navTo = fromHere.filter(e => (e.kind || 'navigate') === 'navigate').map(e => e.to);
      const focusTo = fromHere.filter(e => e.kind === 'setfocus').map(e => e.to);
      main.innerHTML = '<section class="card screen active"><h2>' + escapeHtml(s.name) + '</h2>' +
        '<div class="meta">role=' + escapeHtml(s.role || 'screen') +
        (navTo.length ? ' · navigates to: ' + navTo.map(escapeHtml).join(', ') : '') +
        (focusTo.length ? ' · setfocus: ' + focusTo.map(escapeHtml).join(', ') : '') + '</div>' +
        (s.children || []).map(c => renderControl(c, 0)).join('') +
        '</section>';
    }

    nav.addEventListener('click', (e) => {
      const btn = e.target.closest('.nav-btn');
      if (btn) show(btn.dataset.screen);
    });
    if (screens[0]) show(screens[0].name);
  </script>
</body>
</html>
HTML;
    }
}
